CREATE TABLE PATIENT (
ID VARCHAR PRIMARY KEY NOT NULL,
GENDER VARCHAR NOT NULL,
BIRTHDATE VARCHAR NOT NULL,
DEATHDATE VARCHAR NULL
);

CREATE TABLE ADDRESS (
ADDRESS VARCHAR NULL,
CITY VARCHAR NULL,
STATE VARCHAR NULL,
ZIP VARCHAR NULL,
PATIENT VARCHAR NOT NULL,
FOREIGN KEY(PATIENT) REFERENCES PATIENT(ID)
);

CREATE TABLE PATIENTNAME (
PREFIX VARCHAR NULL,
FIRST VARCHAR NULL,
LAST VARCHAR NULL,
SUFFIX VARCHAR NULL,
PATIENT VARCHAR NOT NULL,
FOREIGN KEY(PATIENT) REFERENCES PATIENT(ID)
);

CREATE TABLE IDENTIFICATION (
SSN VARCHAR NULL,
DRIVERS VARCHAR NULL,
PASSPORT VARCHAR NULL,
PATIENT VARCHAR NOT NULL,
FOREIGN KEY(PATIENT) REFERENCES PATIENT(ID)
);

CREATE TABLE PATIENTDETAILS (
MAIDEN VARCHAR NULL,
MARITAL VARCHAR NULL,
RACE VARCHAR NULL,
ETHNICITY VARCHAR NULL,
BIRTHPLACE VARCHAR NULL,
PATIENT VARCHAR NOT NULL,
FOREIGN KEY(PATIENT) REFERENCES PATIENT(ID)
);